name: CI

on:
  push:
  pull_request:

jobs:
  frontend:
    name: Frontend (lint + test)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('frontend/**') != '' }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            frontend/package.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

  backend:
    name: Backend (lint + test)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('backend/**') != '' }}
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements.txt
            backend/requirements-dev.txt
            backend/pyproject.toml

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # fallbacks if you don't have files yet
          pip install pytest ruff black || true

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Test
        run: pytest -q


